/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.avanzada.parcialsegundocorte.vista;



/**Ventana Del reproductor
 *
 * @author Nicolas
 */
public class Reproductor extends javax.swing.JFrame {

    
    
    /**
     * Creates new form Reproductor
     */
    public Reproductor() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_can = new javax.swing.JList();
        nombre_can = new javax.swing.JTextField();
        btnAnterior = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSliderSonido = new javax.swing.JSlider();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnDetener = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(lista_can);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 260));

        nombre_can.setText("...");
        nombre_can.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(nombre_can, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 460, -1));
        jPanel1.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 50, -1));
        jPanel1.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 50, -1));
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 50, -1));

        jLabel1.setText("hola");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 40, 40));
        jPanel1.add(jSliderSonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        btnAgregar.setText("Agregar Canción");
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        btnQuitar.setText("Quitar Canción");
        jPanel1.add(btnQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 130, -1));

        btnDetener.setText("Detener Reproducción");
        jPanel1.add(btnDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        btnVolver.setText("Volver");
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnAnterior;
    public javax.swing.JButton btnDetener;
    public javax.swing.JButton btnPlay;
    public javax.swing.JButton btnQuitar;
    public javax.swing.JButton btnSiguiente;
    public javax.swing.JButton btnVolver;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSlider jSliderSonido;
    public javax.swing.JList lista_can;
    public javax.swing.JTextField nombre_can;
    // End of variables declaration//GEN-END:variables
}
